set_mode:
  description: Set operation mode of the EVSE
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "garo_wallbox.garage"
    mode:
      description: New mode.

set_current_limit:
  description: Set current charge limit
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "garo_wallbox.garage"
    limit:
      description: New limit.
